### ISSUE TITLE
Can't access UUIDFetcher method while trying to elevate user

### ISSUE THREAD

**Issue by ParkerKemp** [ParkerKemp/Slipdisk#2]
UsernameHistory plugin is working fine. I can do /original. Slipdisk also seems to be working for the most part. The issue may be with the anonymous inner class com.spinalcraft.slipdisk.Slipdisk$2 not being loaded on time. Overwrote .jar file while server was still running? Probably just need to load the class preemptively on startup.

[09:30:38 WARN]: Unexpected exception while parsing console command "elevate Trophxis donor"
org.bukkit.command.CommandException: Unhandled exception executing command 'elevate' in plugin Slipdisk v1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-0b997a9-30d751b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-0b997a9-30d751b]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-0b997a9-30d751b]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchServerCommand(CraftServer.java:632) [spigot.jar:git-Spigot-0b997a9-30d751b]
        at net.minecraft.server.v1_8_R2.DedicatedServer.aN(DedicatedServer.java:405) [spigot.jar:git-Spigot-0b997a9-30d751b]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:369) [spigot.jar:git-Spigot-0b997a9-30d751b]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-0b997a9-30d751b]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-0b997a9-30d751b]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
Caused by: java.lang.IllegalAccessError: tried to access method com.spinalcraft.usernamehistory.UUIDFetcher.fetch(Ljava/lang/String;)Ljava/util/UUID; from class com.spinalcraft.slipdisk.Slipdisk$2
        at com.spinalcraft.slipdisk.Slipdisk$2.run(Slipdisk.java:347) ~[?:?]
        at com.spinalcraft.slipdisk.Slipdisk.elevateUser(Slipdisk.java:342) ~[?:?]
        at com.spinalcraft.slipdisk.Slipdisk.onCommand(Slipdisk.java:115) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-0b997a9-30d751b]
        ... 8 more

**Comment by ParkerKemp** [comment]
UUIDFetcher.fetch() had been privatized and replaced with getUUIDOf().
